export const CHANGE_SEARCH_FOCUS = 'header/CHANGE_SEARCH_FOCUS'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const CHANGE_MOUSE_STATE = 'header/CHANGE_MOUSE_STATE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'
export const CHANGE_SHOW_CARD = 'header/CHANGE_SHOW_CARD'